use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use rat_config::GeneratedConfig;

use crate::ids::parse_fingerprint_hex;
use crate::SyncError;

pub(crate) fn write_generated_header(
    path: &Path,
    generated: &GeneratedConfig,
) -> Result<(), SyncError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| SyncError::WriteHeader {
            path: path.to_path_buf(),
            source,
        })?;
    }

    let mut out = String::new();
    out.push_str("#ifndef RAT_GEN_H\n");
    out.push_str("#define RAT_GEN_H\n\n");
    out.push_str("/* This file is generated by rat-sync. */\n");
    let header_fingerprint = parse_fingerprint_hex(&generated.meta.fingerprint).unwrap_or(0);
    let _ = writeln!(
        out,
        "#define RAT_GEN_FINGERPRINT 0x{:016X}ULL",
        header_fingerprint
    );
    let _ = writeln!(
        out,
        "#define RAT_GEN_PACKET_COUNT {}u",
        generated.packets.len()
    );
    out.push('\n');

    let mut name_counts: HashMap<String, usize> = HashMap::new();
    for packet in &generated.packets {
        let base = macroize_struct_name(&packet.struct_name);
        let count = name_counts
            .entry(base.clone())
            .and_modify(|value| *value += 1)
            .or_insert(1);
        let macro_name = if *count == 1 {
            format!("RAT_ID_{base}")
        } else {
            format!("RAT_ID_{}_{}", base, count)
        };
        let _ = writeln!(out, "#define {macro_name} 0x{:02X}u", packet.id);
    }

    out.push_str("\n#endif  /* RAT_GEN_H */\n");

    fs::write(path, out).map_err(|source| SyncError::WriteHeader {
        path: path.to_path_buf(),
        source,
    })
}

pub(crate) fn macroize_struct_name(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }

    while out.contains("__") {
        out = out.replace("__", "_");
    }

    out.trim_matches('_').to_string()
}
