#ifndef RAT_GEN_H
#define RAT_GEN_H

/* This file is generated by rat-sync. */
#define RAT_GEN_FINGERPRINT 0x6DC228D8526C7443ULL
#define RAT_GEN_PACKET_COUNT 4u

#define RAT_ID_ATTITUDE 0x74u
#define RAT_ID_TEMPERATURE 0x22u
#define RAT_ID_WAVEFORM 0x76u
#define RAT_ID_IMAGESTATS 0xD9u

#endif  /* RAT_GEN_H */
